#!/bin/bash

install_path=/opt/starbound-frackin-universe
config_path=$HOME/.config/starbound-frackin-universe
save_path=$HOME/.local/share/starbound-frackin-universe

mkdir -p $config_path
mkdir -p $save_path

if [ ! -f $config_path/sbinit.config ]
then
    cat > $config_path/sbinit.config <<EOF
{
  "assetDirectories" : [
    "$install_path/assets/",
    "$install_path/mods/"
  ],

  "storageDirectory" : "$save_path"
}
EOF
fi

cd $config_path
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$install_path/linux $install_path/linux/starbound -bootconfig $config_path/sbinit.config

